%%=========================================================================
% MTEX (5.1.1) script for plotting the IPFs associated with the RVE
% generated by DREAM.3D
%
% Author: S. Amir H. Motaman
%         Steel Institute (IEHK), RWTH Aachen University
%
% Reference:
%    Motaman, S.A.H.; Roters, F.; Haase, C.; 2019. Acta Materialia.
%    Anisotropic polycrystal plasticity due to microstructural heterogeneity:
%    A multi-scale experimental and numerical study on additively
%    manufactured metallic materials.
%%=========================================================================

%% Input parameters

% Working directory
working_directory = pwd;

% Specifying the file (containing the Euler angles or the RVE) to be imported
input_file_name = [working_directory '\EulerAngles.txt'];


%% Importing the Euler angles and creating the ODF

% Crystal symmetry
% cs = crystalSymmetry('1', [1 1 1], [90,90,90]*degree, 'X||a', 'Y||b*', 'Z||c*');
cs = crystalSymmetry('m-3m', [1 1 1], 'color', 'light blue');

% Specimen symmetry
ss = specimenSymmetry('1');

% Plotting convention
setMTEXpref('xAxisDirection','east');
setMTEXpref('zAxisDirection','outOfPlane');

% Specifying kernel
psi = deLaValeePoussinKernel('halfwidth',10*degree);

% Creating an EBSD variable containing the data
odf_RVE = loadODF(input_file_name,cs,ss,'density','kernel',psi,'resolution',5*degree,...
          'interface','generic','ColumnNames', { 'phi1' 'Phi' 'phi2'}, 'Bunge', 'Radians');

%% Rotation of data if necessary

% rot = rotation('axis',zvector,'angle',90*degree);
% odf_RVE = rotate(odf_RVE,rot);

%% Ploting the IPFs

figure
plotIPDF(odf_RVE,[xvector,yvector,zvector],'antipodal','contours',20,'LineStyle','-','fill','on','linecolor','w')
mtexColorbar
CLim(gcm,'equal')
% CLim(gcm,[0.85,1.45])
mtexColorbar
mtexColorbar

% annotate([Miller(1,-1,-1,odf.CS)],'label',{'111'},'BackgroundColor','w','Tag','setAboveMarker','FontSize',30)
% annotate([Miller(0, 0, 1,odf.CS)],'label',{'001'},'BackgroundColor','w','Tag','setBelowMarker','FontSize',30)
% annotate([Miller(0, 1, 1,odf.CS)],'label',{'011'},'BackgroundColor','w','Tag','setBelowMarker','FontSize',30)
